# Generated by Django 4.1.4 on 2023-01-07 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solitude_clusters',
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('host', models.CharField(default='', max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
                ('cluster', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.cluster')),
                ('created_by', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solitude_brokers',
            },
        ),
    ]
