# Generated by Django 4.1.3 on 2022-11-21 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('bootstrap_server_host', models.CharField(default='', max_length=255)),
                ('bootstrap_server_port', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solitude_clusters',
            },
        ),
    ]
