# Generated by Django 4.1.3 on 2022-11-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitude', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='server',
            name='host',
        ),
        migrations.AddField(
            model_name='server',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
