# Generated by Django 4.1.3 on 2022-11-21 20:58

from django.db import migrations

def seed_cluster(apps, schema_editor):
    Cluster = apps.get_model('solitude', 'Cluster')
    Cluster = Cluster(title='Local', bootstrap_server_host='localhost', bootstrap_server_port=9092, active=True)
    Cluster.save()

class Migration(migrations.Migration):

    dependencies = [
        ('solitude', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_cluster)
    ]
