# Generated by Django 4.1.3 on 2022-11-15 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solitude', '0003_server_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='title',
        ),
        migrations.AlterField(
            model_name='server',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Notes'),
        ),
    ]
