# Generated by Django 4.1.3 on 2022-11-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solitude', '0002_alter_cluster_created_by'),
        ('solitude', '0003_auto_20221121_2058'),
    ]

    operations = [
    ]
